gaia-dev:
  module: "src.server.tasks.gaia.GAIATask"
  parameters:
    name: "gaia-dev"
    concurrency: 2
    round_limit: 20
    dataset_type: "validation"
    level: "level1"
    data_dir: "data/gaia"
    max_rounds: 15